### ISSUE TITLE
Integer division by zero

### ISSUE THREAD

**Issue by GuoJiaxing267** [Milittle/GaitSystem#1]
我按照您的步骤来的，编译时不报错，运行时加载模型按钮选择数据集后，程序崩溃。断点指在MatchImage.cpp第124行。具体错误为：0xc0000094;Integer division by zero.

**Comment by Milittle** [comment]
> 我按照您的步骤来的，编译时不报错，运行时加载模型按钮选择数据集后，程序崩溃。断点指在MatchImage.cpp第124行。具体错误为：0xc0000094;Integer division by zero.

请问你load进去的数据集是一个剪影序列么？

**Comment by GuoJiaxing267** [comment]
就是按照您给的视频教程操作的，数据集也是下的您的。GaitDatasetB-silh\001\nm-01\090这个目录。加载时选到这个目录后也是什么都没有显示出来。但是文件夹中有56个序列图片。





------------------ 原始邮件 ------------------
发件人: "Milittle"<notifications@github.com>;
发送时间: 2019年6月2日(星期天) 晚上7:08
收件人: "Milittle/GaitSystem"<GaitSystem@noreply.github.com>;
抄送: "放狼的兴兴"<1141958382@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Milittle/GaitSystem] Integer division by zero (#1)



 
我按照您的步骤来的，编译时不报错，运行时加载模型按钮选择数据集后，程序崩溃。断点指在MatchImage.cpp第124行。具体错误为：0xc0000094;Integer division by zero.
  
请问你load进去的数据集是一个剪影序列么？

**Comment by Milittle** [comment]
> 就是按照您给的视频教程操作的，数据集也是下的您的。GaitDatasetB-silh\001\nm-01\090这个目录。加载时选到这个目录后也是什么都没有显示出来。但是文件夹中有56个序列图片。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Milittle"<notifications@github.com>; 发送时间: 2019年6月2日(星期天) 晚上7:08 收件人: "Milittle/GaitSystem"<GaitSystem@noreply.github.com>; 抄送: "放狼的兴兴"<1141958382@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [Milittle/GaitSystem] Integer division by zero (#1) 我按照您的步骤来的，编译时不报错，运行时加载模型按钮选择数据集后，程序崩溃。断点指在MatchImage.cpp第124行。具体错误为：0xc0000094;Integer division by zero. 请问你load进去的数据集是一个剪影序列么？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

有可能是你的cv imread中出现的问题，你看下在opencv中读取的图片大小是多少？按道理是要有非零值的。我先把这个bug修复一下。

**Comment by GuoJiaxing267** [comment]
您好，我没有找出来他读的图片大小是多大。。还有个问题想问问您，后边您在这个系统上又加新的功能了么，就是对这个系统做什么优化了么。





------------------ 原始邮件 ------------------
发件人: "Milittle"<notifications@github.com>;
发送时间: 2019年6月3日(星期一) 晚上11:33
收件人: "Milittle/GaitSystem"<GaitSystem@noreply.github.com>;
抄送: "放狼的兴兴"<1141958382@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Milittle/GaitSystem] Integer division by zero (#1)



 
就是按照您给的视频教程操作的，数据集也是下的您的。GaitDatasetB-silh\001\nm-01\090这个目录。加载时选到这个目录后也是什么都没有显示出来。但是文件夹中有56个序列图片。
 …
 ------------------ 原始邮件 ------------------ 发件人: "Milittle"notifications@github.com; 发送时间: 2019年6月2日(星期天) 晚上7:08 收件人: "Milittle/GaitSystem"GaitSystem@noreply.github.com; 抄送: "放狼的兴兴"1141958382@qq.com;"Author"author@noreply.github.com; 主题: Re: [Milittle/GaitSystem] Integer division by zero (#1) 我按照您的步骤来的，编译时不报错，运行时加载模型按钮选择数据集后，程序崩溃。断点指在MatchImage.cpp第124行。具体错误为：0xc0000094;Integer division by zero. 请问你load进去的数据集是一个剪影序列么？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
有可能是你的cv imread中出现的问题，你看下在opencv中读取的图片大小是多少？按道理是要有非零值的。我先把这个bug修复一下。

**Comment by Milittle** [comment]
> 您好，我没有找出来他读的图片大小是多大。。还有个问题想问问您，后边您在这个系统上又加新的功能了么，就是对这个系统做什么优化了么。

暂时还没时间搞 本来打算搞一搞深度学习的识别 但是最近没有太多时间搞

**Comment by GuoJiaxing267** [comment]
嗯嗯，谢谢您这几天的回复，我还想问一下，您有这些图片序列相应的视频么，就是转成图片之前的视频。原视频或者去灰度化之后的。





------------------ 原始邮件 ------------------
发件人: "Milittle"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 下午4:38
收件人: "Milittle/GaitSystem"<GaitSystem@noreply.github.com>;
抄送: "放狼的兴兴"<1141958382@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Milittle/GaitSystem] Integer division by zero (#1)



 
您好，我没有找出来他读的图片大小是多大。。还有个问题想问问您，后边您在这个系统上又加新的功能了么，就是对这个系统做什么优化了么。
  
暂时还没时间搞 本来打算搞一搞深度学习的识别 但是最近没有太多时间搞

**Comment by Milittle** [comment]
> 嗯嗯，谢谢您这几天的回复，我还想问一下，您有这些图片序列相应的视频么，就是转成图片之前的视频。原视频或者去灰度化之后的。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Milittle"<notifications@github.com>; 发送时间: 2019年6月5日(星期三) 下午4:38 收件人: "Milittle/GaitSystem"<GaitSystem@noreply.github.com>; 抄送: "放狼的兴兴"<1141958382@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [Milittle/GaitSystem] Integer division by zero (#1) 您好，我没有找出来他读的图片大小是多大。。还有个问题想问问您，后边您在这个系统上又加新的功能了么，就是对这个系统做什么优化了么。 暂时还没时间搞 本来打算搞一搞深度学习的识别 但是最近没有太多时间搞 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

你可以在官方网站http://www.cbsr.ia.ac.cn/china/Gait%20Databases%20CH.asp 申请下载
